filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/scrubber/access.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      service: scrubber-gateway
      log_type: access
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/scrubber/error.log
    fields:
      service: scrubber-gateway
      log_type: error
    fields_under_root: true

output.elasticsearch:
  hosts: ["192.168.0.120:9200"]
  index: "scrubber-nginx-%{+yyyy.MM.dd}"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
